# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 616)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_loadScrap = QtWidgets.QPushButton(Form)
        self.btn_loadScrap.setObjectName("btn_loadScrap")
        self.verticalLayout_2.addWidget(self.btn_loadScrap)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lb_image = QtWidgets.QLabel(Form)
        self.lb_image.setMinimumSize(QtCore.QSize(300, 200))
        self.lb_image.setMaximumSize(QtCore.QSize(600, 600))
        self.lb_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_image.setObjectName("lb_image")
        self.horizontalLayout.addWidget(self.lb_image)
        self.lb_screenshot = QtWidgets.QLabel(Form)
        self.lb_screenshot.setMinimumSize(QtCore.QSize(200, 200))
        self.lb_screenshot.setText("")
        self.lb_screenshot.setObjectName("lb_screenshot")
        self.horizontalLayout.addWidget(self.lb_screenshot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.group_selector = QtWidgets.QGroupBox(Form)
        self.group_selector.setEnabled(True)
        self.group_selector.setMinimumSize(QtCore.QSize(270, 200))
        self.group_selector.setMaximumSize(QtCore.QSize(320, 16777215))
        self.group_selector.setAutoFillBackground(False)
        self.group_selector.setTitle("")
        self.group_selector.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.group_selector.setFlat(True)
        self.group_selector.setCheckable(False)
        self.group_selector.setObjectName("group_selector")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.group_selector)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 331, 439))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setContentsMargins(0, 0, 20, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.elemSelect = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elemSelect.sizePolicy().hasHeightForWidth())
        self.elemSelect.setSizePolicy(sizePolicy)
        self.elemSelect.setMinimumSize(QtCore.QSize(310, 250))
        self.elemSelect.setMaximumSize(QtCore.QSize(440, 400))
        self.elemSelect.setObjectName("elemSelect")
        self.elemSelect.setColumnCount(3)
        self.elemSelect.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.elemSelect.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.elemSelect.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.elemSelect.setHorizontalHeaderItem(2, item)
        self.verticalLayout_4.addWidget(self.elemSelect)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_last = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_last.setObjectName("btn_last")
        self.horizontalLayout_3.addWidget(self.btn_last)
        self.curIdx = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.curIdx.setObjectName("curIdx")
        self.horizontalLayout_3.addWidget(self.curIdx)
        self.lb_total = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_total.setObjectName("lb_total")
        self.horizontalLayout_3.addWidget(self.lb_total)
        self.btn_next = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_3.addWidget(self.btn_next)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.group_selector)
        self.elemData = QtWidgets.QTableWidget(Form)
        self.elemData.setMinimumSize(QtCore.QSize(400, 0))
        self.elemData.setMaximumSize(QtCore.QSize(400, 16777215))
        self.elemData.setObjectName("elemData")
        self.elemData.setColumnCount(2)
        self.elemData.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.elemData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.elemData.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_2.addWidget(self.elemData)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_loadScrap.setText(_translate("Form", "Load Scrap"))
        self.lb_image.setText(_translate("Form", "Preview"))
        item = self.elemSelect.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Element Type"))
        item = self.elemSelect.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Number"))
        item = self.elemSelect.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Results"))
        self.btn_last.setText(_translate("Form", "Last"))
        self.lb_total.setText(_translate("Form", "of 0000"))
        self.btn_next.setText(_translate("Form", "Next"))
        item = self.elemData.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Field"))
        item = self.elemData.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Value"))

