


DROP TABLE IMG_1;
DROP TABLE IMG_2;
DROP TABLE IMG_3;
DROP TABLE IMG_4;
DROP TABLE IMG_5;
DROP TABLE IMG_6;
DROP TABLE IMG_7;
DROP TABLE IMG_8;
DROP TABLE IMG_9;
DROP TABLE IMG_10;
DROP TABLE IMG_11;
DROP TABLE IMG_12;
DROP TABLE IMG_13;
DROP TABLE IMG_14;
DROP TABLE IMG_15;
DROP TABLE IMG_16;
DROP TABLE IMG_17;
DROP TABLE IMG_18;
DROP TABLE IMG_19;
DROP TABLE IMG_20;
DROP TABLE IMG_21;
DROP TABLE IMG_22;
DROP TABLE IMG_23;
DROP TABLE IMG_24;
DROP TABLE IMG_25;
DROP TABLE IMG_26;
DROP TABLE IMG_27;
DROP TABLE IMG_28;
DROP TABLE IMG_29;
DROP TABLE IMG_30;
DROP TABLE IMG_31;
DROP TABLE IMG_32;
DROP TABLE IMG_33;
DROP TABLE IMG_34;
DROP TABLE IMG_35;

DROP TABLE URL_1;
DROP TABLE URL_2;
DROP TABLE URL_3;
DROP TABLE URL_4;
DROP TABLE URL_5;
DROP TABLE URL_6;
DROP TABLE URL_7;
DROP TABLE URL_8;
DROP TABLE URL_9;
DROP TABLE URL_10;
DROP TABLE URL_11;
DROP TABLE URL_12;
DROP TABLE URL_13;
DROP TABLE URL_14;
DROP TABLE URL_15;
DROP TABLE URL_16;
DROP TABLE URL_17;
DROP TABLE URL_18;
DROP TABLE URL_19;
DROP TABLE URL_20;
DROP TABLE URL_21;
DROP TABLE URL_22;
DROP TABLE URL_23;
DROP TABLE URL_24;
DROP TABLE URL_25;
DROP TABLE URL_26;
DROP TABLE URL_27;
DROP TABLE URL_28;
DROP TABLE URL_29;
DROP TABLE URL_30;
DROP TABLE URL_31;
DROP TABLE URL_32;
DROP TABLE URL_33;
DROP TABLE URL_34;
DROP TABLE URL_35;

DROP TABLE ElementTableRef;


DROP TABLE ScrapSetting;
DROP TABLE TableImg;
DROP TABLE TableUrl;
DROP TABLE sqlite_sequence;

DROP TABLE Entry;