# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1131, 679)
        Dialog.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.lb_scanid = QtWidgets.QLabel(Dialog)
        self.lb_scanid.setObjectName("lb_scanid")
        self.verticalLayout_4.addWidget(self.lb_scanid)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.le_url = QtWidgets.QLineEdit(Dialog)
        self.le_url.setObjectName("le_url")
        self.verticalLayout_2.addWidget(self.le_url)
        self.le_filename = QtWidgets.QLineEdit(Dialog)
        self.le_filename.setObjectName("le_filename")
        self.verticalLayout_2.addWidget(self.le_filename)
        self.le_scanID = QtWidgets.QLineEdit(Dialog)
        self.le_scanID.setObjectName("le_scanID")
        self.verticalLayout_2.addWidget(self.le_scanID)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ck_skipHeader = QtWidgets.QCheckBox(Dialog)
        self.ck_skipHeader.setObjectName("ck_skipHeader")
        self.horizontalLayout_3.addWidget(self.ck_skipHeader)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_runAll = QtWidgets.QPushButton(Dialog)
        self.btn_runAll.setObjectName("btn_runAll")
        self.horizontalLayout_3.addWidget(self.btn_runAll)
        self.btn_map = QtWidgets.QPushButton(Dialog)
        self.btn_map.setObjectName("btn_map")
        self.horizontalLayout_3.addWidget(self.btn_map)
        self.btn_scan = QtWidgets.QPushButton(Dialog)
        self.btn_scan.setObjectName("btn_scan")
        self.horizontalLayout_3.addWidget(self.btn_scan)
        self.btn_runTest = QtWidgets.QPushButton(Dialog)
        self.btn_runTest.setObjectName("btn_runTest")
        self.horizontalLayout_3.addWidget(self.btn_runTest)
        self.btn_export = QtWidgets.QPushButton(Dialog)
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout_3.addWidget(self.btn_export)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lb_webID = QtWidgets.QLabel(Dialog)
        self.lb_webID.setObjectName("lb_webID")
        self.horizontalLayout_2.addWidget(self.lb_webID)
        self.le_elemID = QtWidgets.QLineEdit(Dialog)
        self.le_elemID.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_elemID.sizePolicy().hasHeightForWidth())
        self.le_elemID.setSizePolicy(sizePolicy)
        self.le_elemID.setMaximumSize(QtCore.QSize(157, 16777215))
        self.le_elemID.setObjectName("le_elemID")
        self.horizontalLayout_2.addWidget(self.le_elemID)
        self.btn_openElem = QtWidgets.QPushButton(Dialog)
        self.btn_openElem.setObjectName("btn_openElem")
        self.horizontalLayout_2.addWidget(self.btn_openElem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.console = QtWidgets.QTextBrowser(Dialog)
        self.console.setObjectName("console")
        self.verticalLayout.addWidget(self.console)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Address:"))
        self.label_2.setText(_translate("Dialog", "Filename:"))
        self.lb_scanid.setText(_translate("Dialog", "Scan ID"))
        self.ck_skipHeader.setText(_translate("Dialog", "Skip Header"))
        self.btn_runAll.setText(_translate("Dialog", "Run All"))
        self.btn_map.setText(_translate("Dialog", "Map"))
        self.btn_scan.setText(_translate("Dialog", "Scan"))
        self.btn_runTest.setText(_translate("Dialog", "Test"))
        self.btn_export.setText(_translate("Dialog", "Export"))
        self.lb_webID.setText(_translate("Dialog", "Open xPath:"))
        self.btn_openElem.setText(_translate("Dialog", "Open"))

